export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_DRAWER_OPEN = 'SET_DRAWER_OPEN';
